# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.6.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Delete old files
        run: rm -r /home/pi/Projects/websites/www/portfolio || true

      - name: Copy to WWW
        run: cp -r $GITHUB_WORKSPACE /home/pi/Projects/websites/www/portfolio

      # Runs a set of commands using the runners shell
      - name: Docker compose build and deploy
        working-directory: /home/pi/Projects/websites/www/portfolio
        run: docker compose up --build -d
